config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :colleges do
	resources :branches do
		resources :students 
		end
  end

  resources :students do
 		 collection do
    		get :list_students
  	end
	end

	resources :branches do
		collection do
			get :list_branches
		end
	end

  resources :colleges do
 	  member do
		  get :students
	  end
  end
 
  devise_scope :user do
   root to: "devise/sessions#new"
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :college
  has_many :students
  validates :branch_name, presence: true
end

app/models/college.rb
class College < ApplicationRecord
  has_many :branches
  has_many :students, through: :branches
  validates :name, presence: true
  validates :address, presence: true
  validates :contact, presence: true
  scope :active, -> { where(active_record: true)}
  default_scope { active } 
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :branch
  validates :student_name, presence: true
  validates :student_address, presence: true
  validates :student_sem, presence: true,  numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!	
	def after_sign_in_path_for(resource)
 		colleges_path #your path
	end	

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]
  before_action :set_college, only: [:index, :show, :edit, :update, :destroy, :new, :create]
  # GET /branches
  # GET /branches.json
  def index
    @branches = @college.branches.paginate(page: params[:page],per_page:4)
  end
  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
    respond_to do |format|
      format.js { }
    end
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = @college.branches.new(branch_params)
    @branch.save
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    @branch.update(branch_params)      
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to college_branches_path(@college), notice: 'Branch was successfully destroyed.' }
      format.js { }
    end
  end

	def list_branches
    if params[:branch].blank?
    	@branches = Branch.all.paginate(page: params[:page],per_page:5)
		else
			@branches = Branch.where("branch_name LIKE :prefix ", prefix:"#{params[:branch]}%").paginate(page: params[:page],per_page:5)
    end	
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end
	  def set_college
		  @college=College.find(params[:college_id])
	  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:college_id, :branch_name)
    end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    if params[:name].blank? &&  params[:add].blank?
			@colleges = College.active.all.paginate(page: params[:page],per_page:4)
    elsif !params[:name].blank? &&  !params[:add].blank?
      @colleges = College.where("name LIKE :prefix and address LIKE :add", prefix:"#{params[:name]}%",add:"#{params[:add]}%").paginate(page: params[:page],per_page:4)
		elsif !params[:name].blank?
      @colleges = College.where("name LIKE :prefix ", prefix:"#{params[:name]}%").paginate(page: params[:page],per_page:4)
    elsif !params[:add].blank?
		  @colleges = College.where("address LIKE :add", add:"#{params[:add]}%").paginate(page: params[:page],per_page:4)
   #name: params[:name]).paginate(page: params[:page],per_page:4)
		end
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
    respond_to do |format|
      format.js { }
    end
  end

  # GET /colleges/1/edit
  def edit
  end

   def addnewuser
   end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)
    @college.save
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    @college.update(college_params)    
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.active_record = false
    @college.save
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.js{ }
    end
  end
	def students
    @college = College.find(params[:id])
		@students=Student.joins(:branch).where('branches.college_id=?',params[:id])
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :address, :contact)
    end
   
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
	before_action :set_branch, only: [:index, :new, :show, :edit, :update, :destroy, :create]
  before_action :set_college, only: [:index, :new, :show, :edit, :update, :destroy, :create]

  # GET /students
  # GET /students.json
  def index
    @students = @branch.students.paginate(page: params[:page],per_page:4)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = @branch.students.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = @branch.students.new(student_params)
    @student.save     
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    @student.update(student_params)   
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to college_branch_students_url(@college,@branch), notice: 'Student was successfully destroyed.' }
      format.js { }
    end
  end

	def list_students
    @students = Student.paginate(page: params[:page],per_page:5)
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end
		def set_branch
  		@branch=Branch.find(params[:branch_id])
 		end
		def set_college
			@college=College.find(params[:college_id])
		end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:branch_id, :student_name, :student_address, :student_sem)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
    base_title = "College Manegement"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/branches/_edit.html.haml
= render 'form', branch: @branch

app/views/branches/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h3  Branch 
    .modal-body
      -if branch.errors.any?
        #error_explanation
          %ul
            -branch.errors.full_messages.each do |message|
              %li= message 
      = form_for([@college,@branch], :remote => :true) do |form|
        .field
          = form.label :branch_name
          = form.text_field :branch_name
        %br
        .modal-footer
          .actions
            = form.submit class: "btn btn-primary" 
            = link_to "Cancel", '#' , class: "btn", data: {dismiss: "modal"}

app/views/branches/_new.html.haml
= render 'form', branch: @branch

app/views/branches/_search.html.haml
= form_tag list_branches_branches_path, :method=> :get do 
  = label_tag "Search"
  = text_field_tag "branch"
  = button_tag(type: "Submit", class: "btn btn-primary") do
    Search
    %i.glyphicon.glyphicon-search

app/views/branches/_show.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h3  Branch Details
    .modal-body
      %p
        %strong College:
        = @branch.college.name 
      %p
        %strong Branch name:
        = @branch.branch_name 
    .modal-footer
      .actions
        = link_to 'Edit', edit_college_branch_path(@college,@branch),class: "btn btn-primary", :remote => true
        = link_to "Cancel", '#', class: "btn", data: {dismiss: "modal"}
        
       

app/views/branches/create.js.erb
<% if @branch.errors.blank? %>
  window.location.href= window.location.href;
<% else %>
    $("#product-modal").html("<%= escape_javascript(render "new", branch:@branch) %>");
<%end%>

app/views/branches/destroy.js.erb
$('#branch_<%= @branch.id %>').remove();

app/views/branches/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/branches/index.html.haml
%p#notice
  = notice
%p
  %h3 
    Branches available in 
    = @college.name
%table.table.table-bordered
  %thead
    %tr
      %th College
      %th Branch name
      %th{:colspan =>"4"}
   
  %tbody
    -@branches.each do |branch| 
      %tr{:id =>"branch_#{branch.id}"}
        %td= branch.college.name
        %td= branch.branch_name
        %td= link_to 'Show', [@college,branch], :remote => true 
        %td= link_to 'Edit', edit_college_branch_path(@college,branch), :remote => true 
        %td= link_to 'Destroy',[@college, branch], method: :delete, data: { confirm: 'Are you sure?' } ,:remote => :true
        %td= link_to 'Students', college_branch_students_path(@college,branch) 
%br
= link_to 'Back', colleges_path(@college)
= link_to 'New Branch', new_college_branch_path(@college),:class => "btn btn-success", :remote => true
%br
= will_paginate @branches
#product-modal.modal.fade

app/views/branches/list_branches.html.haml
%p#notice
  = notice 
= render "/branches/search"
-if params[:branch].blank?
  %h4 List of Branches
-else
  %h4 List of Colleges having  
  = params[:branch] 
%table.table.table-bordered
  %thead
    %tr
      %th Branch name
      %th College
  %tbody
    -@branches.each do |branch|
      %tr   
        %td= branch.branch_name
        %td= branch.college.name rescue 'no college found'
= will_paginate @branches
%br

app/views/branches/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/branches/show.js.erb
$("#product-modal").html("<%= escape_javascript(render 'show') %>")
$("#product-modal").modal("show")

app/views/branches/update.js.erb
<% if @branch.errors.blank? %>
  window.location.href= window.location.href;
<% else %>
    $("#product-modal").html("<%= escape_javascript(render "new", branch:@branch) %>");
<%end%>

app/views/colleges/_edit.html.haml
= render 'form', college: @college

app/views/colleges/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h3  College details
    .modal-body
      -if college.errors.any? 
        #error_explanation
          
          %ul
            -college.errors.full_messages.each do |message| 
              %li= message
      = form_for(@college, :remote => :true ) do |form|
        .form-group
          = form.label :name, class:"control-label"
          = form.text_field :name, class: "form-control", :onchange => "render_add();"
        .form-group
          = form.label :address, class:"control-label" 
          = form.text_area :address, class: "form-control"
        .form-group
          = form.label :contact, class:"control-label" 
          = form.text_field :contact, class: "form-control"
        %br
        .modal-footer
          .actions
            = form.submit class: "btn btn-primary" 
            = link_to "Cancel", '#', class: "btn", data: {dismiss: "modal"}
           
           
    

app/views/colleges/_new.html.haml
= render "form", college:@college

app/views/colleges/_search.html.haml
= form_tag colleges_path, :method => :get do 
  = label_tag "name"
  = text_field_tag "name" 
  = label_tag "Address" 
  = text_field_tag "add"
  = button_tag(type: "Submit", class: "btn btn-primary") do
    Search 
    %i.glyphicon.glyphicon-search
 
 	
 

app/views/colleges/_show.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button", } ×
      %h3  College details
    .modal-body
      %p
        %strong Name:
        = @college.name
      %p
        %strong Address:
        = @college.address
      %p
        %strong Contact:
        = @college.contact
    .modal-footer
      = link_to 'Edit', edit_college_path(@college), class: "btn btn-primary", :remote => true 
      = link_to "Cancel", '#' , class: "btn", data: {dismiss: "modal" }

app/views/colleges/addnewuser.html.erb
<h2 align="center">Sign up</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email",class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password",class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password",class: 'form-control' %>
      </div><br/>

      <div class="actions">
        <%= f.submit "Sign up", class:"btn btn-primary"%>
      </div>
    <% end %>
   

  </div>
</div>

app/views/colleges/create.js.erb
<% if @college.errors.blank? %>
  window.location.href= window.location.href;
<% else %>
    $("#product-modal").html("<%=  escape_javascript(render "new",college:@college) %>");
<%end%>

app/views/colleges/destroy.js.erb
$('#college_<%= @college.id %>').remove();




  

  

app/views/colleges/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/colleges/index.html.haml
%p#notice
  =notice
=render "/colleges/search"
%h1 Colleges
%table.table.table-bordered
  %thead
    %tr
      %th name
      %th Address
      %th Contact
      %th{:colspan=>"5"}
  %tbody
    - @colleges.each do |college|
      %tr{:id =>"college_#{college.id}"}
        %td= college.name
        %td= college.address
        %td= college.contact
        %td= link_to 'Show', college,  :remote => true
        %td= link_to 'Edit', edit_college_path(college), :remote => true
        %td= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } ,:remote => :true
        %td= link_to 'Branches', college_branches_path(college) 
        %td= link_to 'Students', students_college_path(college) 
%br
=link_to 'New College', new_college_path, :class =>"btn btn-primary",  :remote => true
%br
= will_paginate @colleges 
= link_to 'disp','#',:onclick => "on_click()"
#product-modal.modal.fade

.dis
  hiii




  

  

app/views/colleges/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/colleges/show.js.erb
$("#product-modal").html("<%= escape_javascript(render 'show') %>")
$("#product-modal").modal("show")

app/views/colleges/students.html.haml
%p#notice
  = notice
%h4 Students of
= @college.name
%table.table.table-bordered
  %thead
    %tr
      %th College
      %th Branch
      %th Student name
      %th Student sem
      %th{:colspan=>"3"}
  %tbody
    -@students.each do |student| 
      %tr
        %td= student.branch.college.name
        %td= student.branch.branch_name
        %td= student.student_name 
        %td= student.student_sem 



 

app/views/colleges/update.js.erb
<% if @college.errors.blank? %>
  window.location.href= window.location.href;
<% else %>
    $("#product-modal").html("<%=  escape_javascript(render "new", college:@college) %>");
<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <h1>College manegenment</h1>
    <nav>
      <% if user_signed_in? %>
        <div id=namec> <%= current_user.email %></div>
			  <div class="nav navbar-nav navbar-right">
          <ul class="nav nav-pills">
            <li><%= link_to "Home",colleges_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Menu <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                  <li><%= link_to "Colleges", colleges_path %> </li>
                  <li><%= link_to "Branches", list_branches_branches_path %></li>
                  <li><%= link_to "Students", list_students_students_path %></li> 
                  <li class="divider"></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <spam class="glyphicon glyphicon-menu-hamburger"></spam><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if  current_user.admin? %>
                  <li><%= link_to "New User", '#' %> </li> 
                  <li><%= link_to "Profile", edit_user_registration_path %> </li> 
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Profile", edit_user_registration_path %> </li> 
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                <%end%>  
                <li class="divider"></li>
              </ul>
            </li>            
            <% else %>
              <div class="nav navbar-nav navbar-right">
                <ul class="nav nav-pills">
                  <li><%= link_to "Home",colleges_path %></li>
                  <li ><%= link_to 'Login', user_session_path %></li>
                </ul>
              </div>
          </ul>
		    </div>
      <%end%>    
    </nav>
  </div>
</header>

app/views/layouts/_shim.html .erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class="alert_div">
  <% unless notice.blank? %>
    <div class="alert alert-success">
      <%= link_to 'x', '#', :class => "close", 'data-dismiss' => "alert" %>
      <%= notice  %>
    </div>
  <% end %>
  <% unless alert.blank? %>
    <p class="alert alert-danger">
       <%= link_to 'x', '#', :class => "close", 'data-dismiss' => "alert" %>
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb.html.erb
<% if @college.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% r.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/students/_edit.html.haml
= render 'form', student: @student 

app/views/students/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h3  Students 
    .modal-body
      = form_for([@college,@branch,@student], :remote => :true) do |form| 
        -if student.errors.any? 
          #error_explanation
            %ul
              -student.errors.full_messages.each do |message| 
                %li= message
        .field  
          = form.label :Student_Name
          = form.text_field :student_name, class: "form-control"                                                                                                   
        .field
          = form.label :Student_address
          = form.text_field :student_address, class: "form-control"
        .field
          = form.label :Student_sem
          = form.number_field :student_sem, class: "form-control"
          %br
        .modal-footer
          .actions
            = form.submit class: "btn btn-primary" 
            = link_to "Cancel", '#' , class: "btn", data: {dismiss: "modal"}

app/views/students/_new.html.haml
= render 'form', student: @student 

app/views/students/_show.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h3  Students 
    .modal-body
      %p
        %strong Branch:
        = @student.branch.branch_name
      %p
        %strong Student name:
        = @student.student_name
      %p
        %strong Student address:
        = @student.student_address
      %p
        %strong Student sem:
        = @student.student_sem 
    .modal-footer  
      = link_to 'Edit', edit_college_branch_student_path(@college,@branch,@student), class:"btn btn-primary", :remote => true
      = link_to "Cancel", '#', class: "btn", data: {dismiss: "modal"}
     
    

app/views/students/create.js.erb
<% if @student.errors.blank? %>
  window.location.href= window.location.href;
<% else %>
    $("#product-modal").html("<%= escape_javascript(render "new", student:@student) %>");
<%end%>

app/views/students/destroy.js.erb
$('#student_<%= @student.id %>').remove();

app/views/students/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")

app/views/students/index.html.haml
%h3
  List of students under 
  = @college.name 
  and Branch
  =@branch.branch_name 
%p#notice
  = notice 
%h1 Students
%table.table.table-bordered
  %thead
    %tr
      %th Student Name 
      %th Branch
      %th Student Address 
      %th Student Sem
      %th{:colspan=>"3"}
  %tbody
   
    -@students.each do |student|
      %tr{:id =>"student_#{student.id}"}
        %td= student.student_name
        %td= student.branch.branch_name
        %td= student.student_address
        %td= student.student_sem
        %td= link_to 'Show', [@college,@branch,student], :remote => true
        %td= link_to 'Edit', edit_college_branch_student_path(@college,@branch,student), :remote => true
        %td= link_to 'Destroy', [@college,@branch,student], method: :delete, data: { confirm: 'Are you sure?' } ,:remote => :true
%br
= link_to 'Back', college_branches_path(@college,@branch)
= link_to 'New Student', new_college_branch_student_path(@college,@branch), :class => "btn btn-primary", :remote => true

%br
= will_paginate @students 
#product-modal.modal.fade

app/views/students/list_students.html.haml
%p#notice 
  = notice
%h3 List of Students
%table.table.table-bordered
  %thead
    %tr
      %th Student name
      %th Branch
      %th College
      %th Student sem
      %th{:colspan => "3"}
  %tbody
    -@students.each do |student| 
      %tr
        %td= student.student_name 
        %td= student.branch.branch_name 
        %td= student.branch.college.name rescue 'no college found'
        %td= student.student_sem
%br
= will_paginate @students 
%br

app/views/students/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/students/show.js.erb
$("#product-modal").html("<%= escape_javascript(render 'show') %>")
$("#product-modal").modal("show")

app/views/students/update.js.erb
<% if @student.errors.blank? %>
  window.location.href= window.location.href;
<% else %>
    $("#product-modal").html("<%= escape_javascript(render "new", student:@student) %>");
<%end%>